services:
  - type: web
    name: flask-blog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-blog-db
          property: connectionString

databases:
  - name: flask-blog-db
    plan: free